### PR TITLE
Adding Vagrantfile, setup for database VM, setup for backend VM.

### PR DESCRIPTION
**Pull request by ghost**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Server VM Setup:
- Install Java, Maven, Tomcat, and Node.js.
- Ensure environment variables are set correctly for Java and Maven.
Database VM Setup:
- Install PostgreSQL.
- Configure PostgreSQL to allow remote connections.

## QA Instructions, Screenshots, Recordings
Tomcat workability: 

Systemctl:
image
Browser Links:
image

### CODE REVIEW

**Review by ybeliche — COMMENTED** [review]
Have you tested if tomcat is working?

**Comment by ghost** [comment]
Systemctl:
image
Browser Links:
image

**Review by ybeliche — APPROVED** [review]
Seems valid

**Review by Serpantiner — APPROVED** [review]
seems working

**Pull request merged**
